exclude: '^docs/conf.py'

repos:
  - repo: git@github.com:pre-commit/pre-commit-hooks.git
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-ast
      - id: check-json
      - id: check-merge-conflict
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
      - id: mixed-line-ending
        args: [ '--fix=auto' ]  # replace 'auto' with 'lf' to enforce Linux/Mac line endings or 'crlf' for Windows

  ## If you want to avoid flake8 errors due to unused vars or imports:
  # - repo: https://github.com/myint/autoflake
  #   rev: v1.4
  #   hooks:
  #   - id: autoflake
  #     args: [
  #       --in-place,
  #       --remove-all-unused-imports,
  #       --remove-unused-variables,
  #     ]

  - repo: local
    hooks:
      - id: flake8
        name: flake8
        description: wemake-python-styleguide enforcement
        entry: flake8
        args: [ "--config=setup.cfg" ]
        language: python
        types: [ python ]
